/**
 * QA-stage additions for `iris_message_diagram` (Epic 21, Story 21.0 —
 * AC 21.0.7/21.0.12; generated by the qa-generate-e2e-tests stage).
 *
 * Complements the dev suite in `diagram.test.ts` WITHOUT duplication:
 *
 *   - completes the input-validation matrix: boundary ACCEPTS (exactly 20
 *     sessionIds; maxRows 1 and 10000) and the remaining rejections (non-integer
 *     maxRows, wrong-typed values, missing sessionIds);
 *   - covers the handler's content fallback branches: an endpoint result with
 *     ZERO diagrams and a defensive result missing the `diagrams` key entirely
 *     (`result.diagrams ?? []`) — both must render "No diagrams generated."
 *     while still returning the endpoint result object verbatim as
 *     `structuredContent` (decision G3: object, never array).
 *
 * Plain `*.test.ts` in the DEFAULT vitest suite (Rule 8 — not the excluded
 * `*.integration.test.ts` suffix).
 */

import { describe, it, expect, beforeEach } from "vitest";
import type { ToolContext } from "@iris-mcp/shared";
import { messageDiagramTool } from "../tools/diagram.js";
import { createMockHttp, createMockCtx, envelope } from "@iris-mcp/shared/test-helpers";

describe("iris_message_diagram QA validation matrix (Story 21.0)", () => {
  // ── Zod boundary accepts ───────────────────────────────────────

  it("should accept exactly 20 sessionIds (upper boundary)", () => {
    const ids = Array.from({ length: 20 }, (_, i) => i + 1);
    const parsed = messageDiagramTool.inputSchema.safeParse({ sessionIds: ids });
    expect(parsed.success).toBe(true);
  });

  it("should accept the maxRows boundary values 1 and 10000", () => {
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: [1], maxRows: 1 }).success,
    ).toBe(true);
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: [1], maxRows: 10000 }).success,
    ).toBe(true);
  });

  // ── Zod rejections completing the matrix ───────────────────────

  it("should reject a non-integer maxRows", () => {
    const parsed = messageDiagramTool.inputSchema.safeParse({
      sessionIds: [1],
      maxRows: 2.5,
    });
    expect(parsed.success).toBe(false);
  });

  it("should reject wrong-typed inputs", () => {
    // string element inside sessionIds
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: ["12"] }).success,
    ).toBe(false);
    // sessionIds not an array at all
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: "12" }).success,
    ).toBe(false);
    // string-typed maxRows
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: [1], maxRows: "500" }).success,
    ).toBe(false);
    // non-string labelMode
    expect(
      messageDiagramTool.inputSchema.safeParse({ sessionIds: [1], labelMode: 5 }).success,
    ).toBe(false);
  });

  it("should reject a request with sessionIds missing entirely", () => {
    const parsed = messageDiagramTool.inputSchema.safeParse({});
    expect(parsed.success).toBe(false);
  });
});

describe("iris_message_diagram handler fallback branches (Story 21.0)", () => {
  let mockHttp: ReturnType<typeof createMockHttp>;
  let ctx: ToolContext;

  beforeEach(() => {
    mockHttp = createMockHttp();
    ctx = createMockCtx(mockHttp);
  });

  it("should render 'No diagrams generated.' when the endpoint returns zero diagrams", async () => {
    const result = { diagrams: [], count: 0 };
    mockHttp.get.mockResolvedValue(envelope(result));

    const toolResult = await messageDiagramTool.handler({ sessionIds: [1] }, ctx);

    expect(toolResult.isError).toBeUndefined();
    expect(toolResult.content).toEqual([
      { type: "text", text: "No diagrams generated." },
    ]);
    // G3: the endpoint result object verbatim, even when empty.
    expect(toolResult.structuredContent).toEqual(result);
    expect(Array.isArray(toolResult.structuredContent)).toBe(false);
  });

  it("should tolerate a result without a diagrams key (defensive ?? [] branch)", async () => {
    const result = { count: 0 };
    mockHttp.get.mockResolvedValue(envelope(result));

    const toolResult = await messageDiagramTool.handler({ sessionIds: [1] }, ctx);

    expect(toolResult.isError).toBeUndefined();
    expect(toolResult.content).toEqual([
      { type: "text", text: "No diagrams generated." },
    ]);
    expect(toolResult.structuredContent).toEqual(result);
  });
});
