// DO NOT EDIT — generated by scripts/gen-governance-baseline.mjs (FROZEN — see below).
/**
 * FROZEN Epic-14 foundation governance baseline (architecture decision D3 +
 * Story 15.1 AC 15.1.7, frozen-foundation model, lead 2026-06-16).
 *
 * This is the IMMUTABLE Epic-14 foundation snapshot (141 keys, hash
 * `1e62c5ad5bf7`): the set of governance keys that existed at the end of the
 * Epic-14 foundation — a bare tool name for each single-operation tool, and
 * `tool:action` for each value of a multi-action tool's `action` enum.
 *
 * It is the mechanical proof of back-compat (Rule #18, output-only): membership
 * here marks an action as PRE-EXISTING (grandfathered → enabled by the default
 * seed). Anything NOT in the baseline is NEW, and the default seed classifies it
 * by its `mutates` metadata (new read enabled, new write disabled). See
 * `governance.ts` for the seed/cascade logic.
 *
 * **DO NOT regenerate this file to GROW it with post-foundation (Epic 15+)
 * tools.** The frozen-foundation decision (AC 15.1.7) is deliberate: a NEW
 * write tool MUST be ABSENT from this baseline so `defaultSeed` default-disables
 * it. New tool keys are governed by `mutates` + defaultSeed, NOT by baseline
 * membership. Adding them here would re-grandfather every new write as
 * enabled-by-default and break the opt-in-write guarantee. The companion drift
 * test (`governance.test.ts`) is one-directional: it asserts every frozen
 * foundation key still exists in the live surface, and EXPECTS new
 * post-foundation keys to live outside this set.
 *
 * The generator may still be RE-RUN to RE-VERIFY the frozen foundation hash
 * (`1e62c5ad5bf7`) against the Epic-14 tool surface, but must never be committed
 * with post-foundation tools merged in.
 */

/**
 * Short SHA-256 fingerprint of the sorted baseline keys. Changes whenever the
 * governed action surface changes; useful for drift detection / changelogs.
 */
export const GOVERNANCE_BASELINE_HASH = "1e62c5ad5bf7";

/**
 * Every governance key that existed at generation time. Used by the default
 * seed to grandfather pre-existing actions as enabled.
 */
export const GOVERNANCE_BASELINE: ReadonlySet<string> = new Set([
  "iris_alerts_manage:reset",
  "iris_analytics_cubes:build",
  "iris_analytics_cubes:list",
  "iris_analytics_cubes:sync",
  "iris_analytics_mdx",
  "iris_audit_events",
  "iris_config_manage:export",
  "iris_config_manage:get",
  "iris_config_manage:set",
  "iris_credential_list",
  "iris_credential_manage:create",
  "iris_credential_manage:delete",
  "iris_credential_manage:update",
  "iris_database_check",
  "iris_database_list",
  "iris_database_manage:create",
  "iris_database_manage:delete",
  "iris_database_manage:modify",
  "iris_doc_compile",
  "iris_doc_convert",
  "iris_doc_delete",
  "iris_doc_export",
  "iris_doc_get",
  "iris_doc_index",
  "iris_doc_list",
  "iris_doc_load",
  "iris_doc_put",
  "iris_doc_search",
  "iris_doc_xml_export:export",
  "iris_doc_xml_export:import",
  "iris_doc_xml_export:list",
  "iris_docdb_document:delete",
  "iris_docdb_document:get",
  "iris_docdb_document:insert",
  "iris_docdb_document:update",
  "iris_docdb_find",
  "iris_docdb_manage:create",
  "iris_docdb_manage:drop",
  "iris_docdb_manage:list",
  "iris_docdb_property:create",
  "iris_docdb_property:drop",
  "iris_docdb_property:index",
  "iris_ecp_status",
  "iris_execute_classmethod",
  "iris_execute_command",
  "iris_execute_tests",
  "iris_global_get",
  "iris_global_kill",
  "iris_global_list",
  "iris_global_set",
  "iris_interop_rest:create",
  "iris_interop_rest:delete",
  "iris_interop_rest:get",
  "iris_jobs_list",
  "iris_journal_info",
  "iris_license_info",
  "iris_locks_list",
  "iris_lookup_manage:delete",
  "iris_lookup_manage:get",
  "iris_lookup_manage:set",
  "iris_lookup_transfer:export",
  "iris_lookup_transfer:import",
  "iris_macro_info",
  "iris_mapping_list",
  "iris_mapping_manage:create",
  "iris_mapping_manage:delete",
  "iris_metrics_alerts",
  "iris_metrics_interop",
  "iris_metrics_system",
  "iris_mirror_status",
  "iris_namespace_list",
  "iris_namespace_manage:create",
  "iris_namespace_manage:delete",
  "iris_namespace_manage:modify",
  "iris_oauth_list",
  "iris_oauth_manage:create",
  "iris_oauth_manage:delete",
  "iris_oauth_manage:discover",
  "iris_package_list",
  "iris_permission_check",
  "iris_production_adapters",
  "iris_production_autostart:get",
  "iris_production_autostart:set",
  "iris_production_control:recover",
  "iris_production_control:restart",
  "iris_production_control:start",
  "iris_production_control:stop",
  "iris_production_control:update",
  "iris_production_item:disable",
  "iris_production_item:enable",
  "iris_production_item:get",
  "iris_production_item:set",
  "iris_production_logs",
  "iris_production_manage:create",
  "iris_production_manage:delete",
  "iris_production_messages",
  "iris_production_queues",
  "iris_production_status",
  "iris_production_summary",
  "iris_resource_list",
  "iris_resource_manage:create",
  "iris_resource_manage:delete",
  "iris_resource_manage:modify",
  "iris_rest_manage:delete",
  "iris_rest_manage:get",
  "iris_rest_manage:list",
  "iris_role_list",
  "iris_role_manage:create",
  "iris_role_manage:delete",
  "iris_role_manage:modify",
  "iris_routine_intermediate",
  "iris_rule_get",
  "iris_rule_list",
  "iris_server_info",
  "iris_server_namespace",
  "iris_sql_execute",
  "iris_ssl_list",
  "iris_ssl_manage:create",
  "iris_ssl_manage:delete",
  "iris_ssl_manage:modify",
  "iris_task_history",
  "iris_task_list",
  "iris_task_manage:create",
  "iris_task_manage:delete",
  "iris_task_manage:modify",
  "iris_task_run",
  "iris_transform_list",
  "iris_transform_test",
  "iris_user_get",
  "iris_user_manage:create",
  "iris_user_manage:delete",
  "iris_user_manage:modify",
  "iris_user_password:change",
  "iris_user_password:validate",
  "iris_user_roles:add",
  "iris_user_roles:remove",
  "iris_webapp_get",
  "iris_webapp_list",
  "iris_webapp_manage:create",
  "iris_webapp_manage:delete",
  "iris_webapp_manage:modify",
]);
