// ════════════════════════════════════════════════════════════════════════════
// gen-skills.mjs (Epic 25, Story 25.1, AC 25.1.2)
//
// Generates the installable `skills/` directory from the prompt content
// authored ONCE in `packages/{ops,dev,interop,admin}-mcp/src/prompts/*.ts`
// (single source of truth per spec `03-skills-prompts-pack.md` §3). Every
// generated file carries a DO-NOT-EDIT header (Rule #18).
//
// UNLIKE `scripts/gen-governance-baseline.mjs`, `skills/` is NOT a frozen
// artifact (Rule #23/#25 do not apply here) — the default (no-flag) mode
// WRITES. `--check` is the CI / no-write verification mode (Rule #25
// shape): it re-derives the expected content from source and diffs against
// the on-disk `skills/` tree WITHOUT writing, failing (exit 1) on ANY drift
// — including a hand-edited generated file, a missing generated file, or a
// stale file left over from a removed prompt.
//
// USAGE:
//   node scripts/gen-skills.mjs            Regenerate skills/ from source (writes).
//   node scripts/gen-skills.mjs --check    No-write drift verification (CI-safe).
//
//   npm: `pnpm gen:skills` / `pnpm gen:skills:check`
//
// Requires a prior `pnpm turbo run build` (imports each package's BUILT
// dist/prompts/index.js — see scripts/lib/prompt-catalog.mjs).
// ════════════════════════════════════════════════════════════════════════════

import { writeFileSync, mkdirSync, readFileSync, existsSync, readdirSync, rmSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { loadAllPrompts } from './lib/prompt-catalog.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const argv = process.argv.slice(2);
const CHECK_MODE = argv.includes('--check');

const skillsDir = resolve(root, 'skills');

/** DO-NOT-EDIT header text shared by every generated file (Rule #18). */
function doNotEditHeader(sourceNote) {
  return (
    `<!-- DO NOT EDIT — generated by scripts/gen-skills.mjs from ${sourceNote}.\n` +
    `     Regenerate via: pnpm gen:skills -->\n`
  );
}

/**
 * Render one prompt's `skills/<name>/SKILL.md` content. Claude Code skill
 * format: YAML frontmatter (`name`, `description`) followed by the prompt
 * body. The body is rendered via `build({})` — every Story 25.1 prompt
 * falls back to a bracketed `<argName>` placeholder per omitted argument,
 * so the static skill doc reads as a readable parameterized template.
 */
function renderSkillMd(pkg, prompt) {
  const frontHeader =
    `# DO NOT EDIT — generated by scripts/gen-skills.mjs from\n` +
    `# packages/${pkg}/src/prompts/*.ts (source prompt: "${prompt.name}").\n` +
    `# Regenerate via: pnpm gen:skills\n`;
  const frontmatter =
    `---\n${frontHeader}name: ${prompt.name}\ndescription: ${JSON.stringify(prompt.description)}\n---\n\n`;
  const body = prompt.build({});
  return `${frontmatter}${body}\n`;
}

/** Render `skills/README.md` — the installable-skills install guide. */
function renderReadme(entries) {
  const header = doNotEditHeader('the registered PromptDefinitions across packages/*/src/prompts/*.ts');
  const rows = entries
    .map(({ pkg, prompt }) => `| \`${prompt.name}\` | ${pkg} | ${prompt.description} |`)
    .join('\n');
  return (
    `${header}\n` +
    `# IRIS MCP Agent Skills Pack\n\n` +
    `This directory is **generated** from the suite's MCP \`prompts\` capability (Epic 25) — the ` +
    `same content served by \`prompts/list\` / \`prompts/get\` on each IRIS MCP server, packaged as ` +
    `installable Claude Code skills.\n\n` +
    `## Installation\n\n` +
    `Copy the skill directories you want into your project's \`.claude/skills/\` directory (or point ` +
    `your client's skill-loader configuration at this \`skills/\` directory directly):\n\n` +
    `\`\`\`bash\ncp -r skills/<skill-name> /path/to/your/project/.claude/skills/\n\`\`\`\n\n` +
    `Each skill is a self-contained \`SKILL.md\` with YAML frontmatter (\`name\`, \`description\`) ` +
    `followed by the workflow instructions — the exact tool sequence, argument names, and safety notes ` +
    `an MCP client should follow. Tool names referenced in every skill are validated against the live ` +
    `tool catalog by \`scripts/validate-prompts.mjs\` (wired into the default test suite), so a renamed ` +
    `or removed tool breaks CI rather than shipping a broken skill.\n\n` +
    `## Available Skills\n\n` +
    `| Skill | Server | Description |\n` +
    `|---|---|---|\n` +
    `${rows}\n\n` +
    `Prefer calling these workflows via the MCP \`prompts\` capability directly (\`prompts/get\`) when ` +
    `your client supports it — the skill files here are a convenience export for clients that only load ` +
    `local skill directories.\n`
  );
}

/** Every generated file, relative-to-root path -> expected content. */
async function computeExpectedFiles() {
  const entries = await loadAllPrompts(root);
  const files = new Map();
  for (const { pkg, prompt } of entries) {
    files.set(`skills/${prompt.name}/SKILL.md`, renderSkillMd(pkg, prompt));
  }
  files.set('skills/README.md', renderReadme(entries));
  return { entries, files };
}

/** Every `skills/<name>/SKILL.md` currently on disk (for stale-file detection). */
function listOnDiskSkillFiles() {
  const onDisk = new Set();
  if (!existsSync(skillsDir)) return onDisk;
  for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const md = resolve(skillsDir, entry.name, 'SKILL.md');
      if (existsSync(md)) onDisk.add(`skills/${entry.name}/SKILL.md`);
    }
  }
  if (existsSync(resolve(skillsDir, 'README.md'))) {
    onDisk.add('skills/README.md');
  }
  return onDisk;
}

const { entries, files } = await computeExpectedFiles();

if (CHECK_MODE) {
  let drift = false;

  for (const [rel, expected] of files) {
    const abs = resolve(root, rel);
    if (!existsSync(abs)) {
      console.error(`gen-skills --check: MISSING generated file: ${rel}`);
      drift = true;
      continue;
    }
    const actual = readFileSync(abs, 'utf-8');
    if (actual !== expected) {
      console.error(
        `gen-skills --check: DRIFT in ${rel} (hand-edited, or source changed without regenerating).`,
      );
      drift = true;
    }
  }

  // Stale-file detection: an on-disk skill with no corresponding source prompt.
  const onDisk = listOnDiskSkillFiles();
  for (const rel of onDisk) {
    if (!files.has(rel)) {
      console.error(`gen-skills --check: STALE generated file (no source prompt): ${rel}`);
      drift = true;
    }
  }

  if (drift) {
    console.error('');
    console.error('Run "pnpm gen:skills" to regenerate skills/ from source, then commit the result.');
    process.exit(1);
  }

  console.log(`gen-skills --check: OK — ${files.size} generated file(s) match source, no drift.`);
  process.exit(0);
}

// ── Write mode (default) ─────────────────────────────────────────────────
for (const [rel, content] of files) {
  const abs = resolve(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, 'utf-8');
}

// Remove stale skill directories left over from a removed prompt, so the
// tree never silently accumulates orphaned skills (and so --check never
// flags a leftover file this generator itself failed to clean up).
const onDisk = listOnDiskSkillFiles();
for (const rel of onDisk) {
  if (files.has(rel)) continue;
  if (rel === 'skills/README.md') continue; // always regenerated above
  const skillDir = dirname(resolve(root, rel));
  console.log(`gen-skills: removing stale generated skill directory: ${dirname(rel)}/`);
  rmSync(skillDir, { recursive: true, force: true });
}

console.log(`Generated ${files.size} file(s) under skills/ from ${entries.length} prompt(s).`);
