/**
 * QA-stage additions for `iris_env_promote`'s Story 27.2 `plan` action --
 * generated by the qa-generate-e2e-tests stage.
 *
 * Complements the dev suite in `env-promote.test.ts` WITHOUT duplicating it.
 * That suite already proves: 5-domain ordering with a monotonic 1..N index;
 * one warning per `onlyInTarget` entry with zero delete/remove operations
 * (checked via a 2-keyword substring denylist); a 64-char hex `planHash`
 * that is deterministic regardless of TOP-LEVEL and NESTED key order,
 * sensitive to a value change, and idempotent across repeated calls;
 * per-domain step shape (operation/subject/detail/direction); one redaction
 * test (the `[REDACTED:differs]` marker survives, and a generic set of
 * placeholder secrets that were never actually in the diff are absent from
 * `JSON.stringify(structuredContent)`); missing/malformed-`diff` refusal;
 * and the `execute` stub. Governance (plan enabled / execute disabled /
 * registration-doesn't-throw) is fully covered by `env-promote-governance.test.ts`
 * and is NOT duplicated here.
 *
 * This file adds:
 *
 *  - a STRONGER no-delete invariant (AC 27.2.2): an ALLOWLIST check (every
 *    emitted operation must be one of the six known write verbs) rather
 *    than a keyword denylist, a count-based cross-check (steps + warnings
 *    == exactly the entries fed in -- nothing silently dropped or
 *    duplicated), and a check that every `onlyInTarget` subject appears in
 *    the rendered text's "Warnings" section only, never in the "Steps"
 *    section -- exercised across ALL FIVE domains at once so all six
 *    operation verbs and all five warning buckets are covered in one plan;
 *  - a defense-in-depth redaction test: a `differs` SDS entry that carries
 *    BOTH the `redacted` marker AND (hypothetically, as if a future
 *    `iris_env_diff` regression stopped omitting them per Story 27.1's
 *    contract) raw `sourceValue`/`targetValue` fields holding a distinctive
 *    fake secret -- proves the plan generator's `redacted`-branch never
 *    reads those fields at all, so the plaintext cannot leak even if the
 *    upstream contract were ever violated. Checked against the FULL
 *    serialized plan (`structuredContent` AND `content[].text` combined),
 *    not just `structuredContent`;
 *  - ordering with a SPARSE domain set (only 2 of 5 domains present, with a
 *    3rd flagged as errored and 2 simply absent/not requested) -- proves
 *    step domain order + monotonic index are preserved among the present
 *    domains, and that the rendered "Skipped domain(s)" LINE names only the
 *    genuinely errored domain (not the domains that were merely never
 *    requested) -- scoped to that one line, since the render's static
 *    ordering-description header always mentions all five domain names
 *    regardless of what's actually present in this particular plan;
 *  - `plan` and the `execute` stub both make ZERO IRIS/HTTP calls -- `plan`
 *    is architecturally a pure transform (`scope: "NONE"`) and `execute` is
 *    a static stub; this is the mechanical proof for that architectural
 *    claim, worth pinning as a regression guard against a future edit
 *    wiring `ctx.http` into either action prematurely.
 *
 * Mocked-only, no live IRIS (`plan` is a pure transform; `execute` is a
 * static stub -- neither ever calls `ctx.http`). Plain `*.test.ts` in the
 * DEFAULT vitest suite (Rule 8 / Rule #21 -- not the excluded
 * `*.integration.test.ts` suffix).
 */

import { describe, it, expect, vi } from "vitest";
import type { ToolResult } from "@iris-mcp/shared";
import { envPromoteTool } from "../tools/env-promote.js";
import { createMockCtx } from "./test-helpers.js";

const ctx = createMockCtx();

/** Full serialized result (structuredContent JSON + all content[].text) -- the surface a leaked secret or a forbidden operation must never appear in. */
function serializedResult(result: ToolResult): string {
  return JSON.stringify(result.structuredContent) + "\n" + result.content.map((c) => c.text ?? "").join("\n");
}

/** The complete, closed set of write verbs `buildPlan` is allowed to emit (AC 27.2.1 Task 2). */
const KNOWN_SAFE_OPERATIONS = new Set([
  "createMapping",
  "updateMapping",
  "putAndCompile",
  "setDefaultSetting",
  "modifyWebApp",
  "setConfig",
]);

/**
 * A diff with ONE `onlyInSource` + ONE `differs` + ONE `onlyInTarget` entry
 * in EVERY domain (15 entries total -- 10 step-producing, 5
 * warning-producing), so the assertions below exercise all six operation
 * verbs and all five warning buckets in a single plan.
 */
function fiveDomainMixedDiff(): Record<string, unknown> {
  return {
    source: { profile: "stage", namespace: "HSCUSTOM" },
    target: { profile: "prod", namespace: "HSCUSTOM" },
    domains: {
      mappings: {
        onlyInSource: ["global::HSCUSTOM::NewGlobal"],
        onlyInTarget: ["global::HSCUSTOM::TargetOnlyGlobal"],
        differs: [
          {
            type: "global",
            namespace: "HSCUSTOM",
            name: "ChangedGlobal",
            sourceValue: { database: "A" },
            targetValue: { database: "B" },
          },
        ],
        identical: 0,
      },
      documents: {
        onlyInSource: ["NewClass.cls"],
        onlyInTarget: ["TargetOnlyClass.cls"],
        differs: [
          { name: "ChangedClass.cls", sourceHash: "a".repeat(64), targetHash: "b".repeat(64), sourceTs: "t1", targetTs: "t2" },
        ],
        identical: 0,
      },
      defaultSettings: {
        onlyInSource: [{ production: "P", item: "I1", hostClass: "H", setting: "NewSetting", value: "v1" }],
        onlyInTarget: [{ production: "P", item: "I2", hostClass: "H", setting: "TargetOnlySetting", value: "v2" }],
        differs: [
          { production: "P", item: "I3", hostClass: "H", setting: "ChangedSetting", sourceValue: "old", targetValue: "new" },
        ],
        identical: 0,
      },
      webapps: {
        onlyInSource: ["/api/new"],
        onlyInTarget: ["/api/target-only"],
        differs: [{ name: "/api/changed", sourceValue: { enabled: true }, targetValue: { enabled: false } }],
        identical: 0,
      },
      config: {
        onlyInSource: ["NewKey"],
        onlyInTarget: ["TargetOnlyKey"],
        differs: [{ key: "ChangedKey", sourceValue: 1, targetValue: 2 }],
        identical: 0,
      },
    },
    summary: { driftCount: 15, identicalCount: 0 },
  };
}

// ══════════════════════════════════════════════════════════════════
// No-delete invariant hardening (AC 27.2.2) -- gaps beyond the dev suite
// ══════════════════════════════════════════════════════════════════

describe("iris_env_promote:plan -- QA hardening: no-delete invariant is exhaustive (AC 27.2.2)", () => {
  it("every emitted operation across all 5 domains is on the write-verb ALLOWLIST -- not merely absent a 'delete'/'remove' substring", async () => {
    const result = await envPromoteTool.handler(
      { action: "plan", source: "stage", target: "prod", diff: fiveDomainMixedDiff() },
      ctx,
    );
    expect(result.isError).toBeFalsy();
    const structured = result.structuredContent as { steps: Array<{ operation: string }> };

    expect(structured.steps.length).toBeGreaterThan(0);
    for (const step of structured.steps) {
      expect(KNOWN_SAFE_OPERATIONS.has(step.operation)).toBe(true);
    }
    // Belt-and-braces: also scan for a wider set of destructive verbs by name
    // (the allowlist check above is the strong guarantee; this is a
    // human-readable regression trip-wire for the same property).
    const opsText = structured.steps.map((s) => s.operation.toLowerCase()).join(",");
    for (const forbidden of ["delete", "remove", "drop", "purge", "wipe", "truncate", "kill", "destroy"]) {
      expect(opsText).not.toContain(forbidden);
    }
  });

  it("count-based cross-check: exactly (onlyInSource+differs) entries become steps and exactly onlyInTarget entries become warnings -- nothing dropped or duplicated", async () => {
    const result = await envPromoteTool.handler(
      { action: "plan", source: "stage", target: "prod", diff: fiveDomainMixedDiff() },
      ctx,
    );
    const structured = result.structuredContent as {
      steps: unknown[];
      warnings: unknown[];
      summary: { stepCount: number; warningCount: number };
    };
    // 5 domains x (1 onlyInSource + 1 differs) = 10 steps; 5 domains x 1 onlyInTarget = 5 warnings.
    expect(structured.steps).toHaveLength(10);
    expect(structured.warnings).toHaveLength(5);
    expect(structured.summary).toEqual({ stepCount: 10, warningCount: 5 });
  });

  it("every onlyInTarget subject appears in the rendered text's Warnings section only, never in the Steps section", async () => {
    const result = await envPromoteTool.handler(
      { action: "plan", source: "stage", target: "prod", diff: fiveDomainMixedDiff() },
      ctx,
    );
    const text = result.content[0]?.text ?? "";
    const warningsIdx = text.indexOf("Warnings (");
    expect(warningsIdx).toBeGreaterThan(-1);
    const stepsSection = text.slice(0, warningsIdx);
    const warningsSection = text.slice(warningsIdx);

    const targetOnlySubjects = [
      "global::HSCUSTOM::TargetOnlyGlobal",
      "TargetOnlyClass.cls",
      "P||I2||H||TargetOnlySetting",
      "/api/target-only",
      "TargetOnlyKey",
    ];
    for (const subject of targetOnlySubjects) {
      expect(stepsSection).not.toContain(subject);
      expect(warningsSection).toContain(subject);
    }
  });
});

// ══════════════════════════════════════════════════════════════════
// Redaction survival hardening (spec §4/§7) -- defense-in-depth beyond the dev suite
// ══════════════════════════════════════════════════════════════════

describe("iris_env_promote:plan -- QA hardening: redaction survives even a hypothetical upstream double-custody leak", () => {
  it("a differs SDS entry carrying BOTH the redacted marker AND raw sourceValue/targetValue never leaks the raw fields -- the redacted branch never reads them", async () => {
    const distinctSecret = "zQ7-DISTINCT-FAKE-SECRET-4471";
    const diff = {
      source: { profile: "stage", namespace: "HSCUSTOM" },
      target: { profile: "prod", namespace: "HSCUSTOM" },
      domains: {
        defaultSettings: {
          onlyInSource: [],
          onlyInTarget: [],
          differs: [
            {
              production: "P",
              item: "I",
              hostClass: "H",
              setting: "ApiPassword",
              redacted: "[REDACTED:differs]",
              // Hypothetical: as if a future iris_env_diff regression stopped
              // omitting these fields once `redacted` is set (Story 27.1's
              // contract) -- the plan generator must STILL never read them.
              sourceValue: distinctSecret,
              targetValue: `${distinctSecret}-target`,
            },
          ],
          identical: 0,
        },
      },
      summary: { driftCount: 1, identicalCount: 0 },
    };

    const result = await envPromoteTool.handler({ action: "plan", source: "stage", target: "prod", diff }, ctx);
    expect(result.isError).toBeFalsy();

    const structured = result.structuredContent as { steps: Array<Record<string, unknown>> };
    expect(structured.steps).toHaveLength(1);
    expect(structured.steps[0]?.detail).toBe("update value [REDACTED:differs]");

    const serialized = serializedResult(result);
    expect(serialized).not.toContain(distinctSecret);
    expect(serialized).not.toContain(`${distinctSecret}-target`);
    expect(serialized).toContain("[REDACTED:differs]");
  });
});

// ══════════════════════════════════════════════════════════════════
// Ordering with a sparse domain set + errored-vs-absent distinction (AC 27.2.1)
// ══════════════════════════════════════════════════════════════════

describe("iris_env_promote:plan -- QA hardening: ordering with a SPARSE domain set", () => {
  it("only 2 of 5 domains present (documents, config); a 3rd (mappings) flagged errored -- steps stay domain-ordered with a monotonic index, and the 'Skipped domain(s)' LINE names only the errored domain", async () => {
    const diff = {
      source: { profile: "stage", namespace: "HSCUSTOM" },
      target: { profile: "prod", namespace: "HSCUSTOM" },
      domains: {
        documents: { onlyInSource: ["OnlyDoc.cls"], onlyInTarget: [], differs: [], identical: 0 },
        config: { onlyInSource: ["OnlyConfigKey"], onlyInTarget: [], differs: [], identical: 0 },
        // defaultSettings and webapps are simply ABSENT (never requested) --
        // no entry in `domains`, and no entry in `errors` either.
      },
      errors: { mappings: "Interoperability schema not found" },
      summary: { driftCount: 2, identicalCount: 0 },
    };

    const result = await envPromoteTool.handler({ action: "plan", source: "stage", target: "prod", diff }, ctx);
    expect(result.isError).toBeFalsy();
    const structured = result.structuredContent as { steps: Array<{ index: number; domain: string }> };

    expect(structured.steps.map((s) => s.domain)).toEqual(["documents", "config"]);
    expect(structured.steps.map((s) => s.index)).toEqual([1, 2]);

    // The render's static ordering-description header always names all 5
    // domains (it describes the FIXED scheme, not this plan's contents) --
    // so the "skipped" assertion must be scoped to the specific line that
    // reports errored domains, not the whole text.
    const text = result.content[0]?.text ?? "";
    const skippedLine = text.split("\n").find((l) => l.startsWith("Skipped domain(s)"));
    expect(skippedLine).toBeDefined();
    expect(skippedLine).toContain("mappings");
    expect(skippedLine).not.toContain("defaultSettings");
    expect(skippedLine).not.toContain("webapps");
  });
});

// ══════════════════════════════════════════════════════════════════
// Zero IRIS calls -- `plan` (pure transform) and `execute` (static stub)
// ══════════════════════════════════════════════════════════════════

describe("iris_env_promote -- QA hardening: zero IRIS/HTTP calls from either action in this story", () => {
  it("'plan' never touches ctx.http -- a mechanical proof of the 'pure transform, scope: NONE' architectural claim", async () => {
    const http = ctx.http as unknown as Record<"get" | "put" | "post" | "delete" | "head", ReturnType<typeof vi.fn>>;
    const callsBefore = {
      get: http.get.mock.calls.length,
      put: http.put.mock.calls.length,
      post: http.post.mock.calls.length,
      delete: http.delete.mock.calls.length,
      head: http.head.mock.calls.length,
    };

    await envPromoteTool.handler({ action: "plan", source: "stage", target: "prod", diff: fiveDomainMixedDiff() }, ctx);

    expect(http.get.mock.calls.length).toBe(callsBefore.get);
    expect(http.put.mock.calls.length).toBe(callsBefore.put);
    expect(http.post.mock.calls.length).toBe(callsBefore.post);
    expect(http.delete.mock.calls.length).toBe(callsBefore.delete);
    expect(http.head.mock.calls.length).toBe(callsBefore.head);
  });

  it("'execute' with EVERY optional field supplied at once (plan/steps/confirm/namespace) still just returns the stub refusal -- no ctx.http call, no crash, no partial write attempt", async () => {
    const http = ctx.http as unknown as Record<"get" | "put" | "post" | "delete" | "head", ReturnType<typeof vi.fn>>;
    const callsBefore = {
      get: http.get.mock.calls.length,
      put: http.put.mock.calls.length,
      post: http.post.mock.calls.length,
      delete: http.delete.mock.calls.length,
    };

    const result = await envPromoteTool.handler(
      {
        action: "execute",
        source: "stage",
        target: "prod",
        plan: { planHash: "deadbeef".repeat(8), steps: [1, 2] },
        steps: [1, 2, 3],
        confirm: true,
        namespace: "HSCUSTOM",
      },
      ctx,
    );

    expect(result.isError).toBe(true);
    expect(result.content[0]?.text).toContain("Story 27.3");
    expect(result.structuredContent).toBeUndefined();
    expect(http.get.mock.calls.length).toBe(callsBefore.get);
    expect(http.put.mock.calls.length).toBe(callsBefore.put);
    expect(http.post.mock.calls.length).toBe(callsBefore.post);
    expect(http.delete.mock.calls.length).toBe(callsBefore.delete);
  });
});
