/**
 * QA-stage additions for `iris_env_diff`'s Story 27.1 domains (`mappings`,
 * `defaultSettings`, `webapps`, `config`) — generated by the
 * qa-generate-e2e-tests stage.
 *
 * Complements the dev suite in `env-diff-domains.test.ts` WITHOUT
 * duplicating it. That suite proves each of the 4 new domains' four buckets
 * in isolation, and proves ONE credential setting is redacted in the
 * `differs`, `identical`, and `onlyInSource` buckets. This file adds:
 *
 *  - the credential-redaction bucket the dev suite does NOT exercise:
 *    `onlyInTarget` (AC 27.1.2's easiest-to-miss case — a credential-ish
 *    setting present on only the TARGET side must be redacted too, not
 *    just onlyInSource);
 *  - a "kitchen sink" scenario mixing FOUR differently-shaped credential
 *    settings (password/secret/key/underscore, mixed case) across all four
 *    buckets AT ONCE, alongside a plain non-credential setting, proving the
 *    FULL serialized result (structuredContent AND content[].text combined)
 *    never contains any plaintext secret while the non-credential value
 *    stays visible;
 *  - the redaction contract's NAME-only boundary (AC 27.1.2 dev notes:
 *    "Match on the setting NAME ... NOT the value") — a setting whose VALUE
 *    looks credential-ish under a NON-matching NAME must show its real
 *    value, unredacted;
 *  - per-profile namespace routing for `mappings`/`defaultSettings`: proves
 *    each side's GET call carries ITS OWN resolved namespace on the wire
 *    when `namespace` is omitted. The dev suite proves this for `documents`
 *    (`env-diff.test.ts`) and proves the mapping KEY is `(type, name)` ONLY
 *    -- namespace is NOT part of the identity, so a genuinely-identical
 *    mapping under two differing default namespaces reads as `identical`,
 *    never a spurious per-side collision (cycle-2 HIGH fix, 2026-07-11) --
 *    but never asserts the actual outgoing namespace query param for the
 *    mappings/defaultSettings GET calls;
 *  - a full 5-domain roll-up: `summary.driftCount`/`identicalCount` sum
 *    correctly across ALL FIVE domains at once, each with distinct,
 *    deliberately varied per-domain bucket counts (the dev suite's roll-up
 *    test only covers a 2-domain combination).
 *
 * Mocked-HTTP unit tests only — no live IRIS. Plain `*.test.ts` in the
 * DEFAULT vitest suite (Rule 8 / Rule #21 — not the excluded
 * `*.integration.test.ts` suffix).
 */

import { describe, it, expect, beforeEach, vi } from "vitest";
import type { ToolContext, ToolResult } from "@iris-mcp/shared";
import { ProfileResolutionError } from "@iris-mcp/shared";
import { envDiffTool } from "../tools/env-diff.js";
import { createMockHttp, createMockCtx, envelope } from "./test-helpers.js";

// ── fixture builders (self-contained -- mirrors env-diff-domains.test.ts's shapes) ──

interface MappingRow {
  name: string;
  type: string;
  namespace: string;
  database: string;
  collation?: string;
  lockDatabase?: string;
}

function mappingRow(overrides: Partial<MappingRow> = {}): MappingRow {
  return {
    name: "Test",
    type: "global",
    namespace: "HSCUSTOM",
    database: "IRISDB",
    ...overrides,
  };
}

interface SdsRow {
  id: number;
  production: string;
  item: string;
  hostClass: string;
  setting: string;
  value: string;
}

function sdsRow(overrides: Partial<SdsRow> = {}): SdsRow {
  return {
    id: 1,
    production: "MyProd",
    item: "MyItem",
    hostClass: "MyHost",
    setting: "Timeout",
    value: "30",
    ...overrides,
  };
}

interface WebAppRow {
  name: string;
  namespace: string;
  dispatchClass: string;
  description: string;
  enabled: boolean;
  authEnabled: number;
  isNameSpaceDefault: boolean;
  cspZenEnabled: boolean;
  recurse: boolean;
  matchRoles: string;
  cookiePath: string;
}

function webappRow(overrides: Partial<WebAppRow> = {}): WebAppRow {
  return {
    name: "/api/test",
    namespace: "HSCUSTOM",
    dispatchClass: "My.Dispatch",
    description: "",
    enabled: true,
    authEnabled: 32,
    isNameSpaceDefault: false,
    cspZenEnabled: false,
    recurse: true,
    matchRoles: "%DB_HSCUSTOM",
    cookiePath: "/api/test/",
    ...overrides,
  };
}

function configProps(overrides: Partial<Record<string, number | string>> = {}) {
  return {
    Maxprocesses: 100,
    globals: 100,
    routines: 100,
    gmheap: 100,
    locksiz: 100,
    jrnbufs: 100,
    console: "en",
    errlog: 100,
    wdparm: 100,
    ijcnum: 100,
    ijcbuff: 100,
    ...overrides,
  };
}

// ── structuredContent shapes (test-local) ───────────────────────────────

interface SdsEntrySC {
  production: string;
  item: string;
  hostClass: string;
  setting: string;
  value?: string;
  sourceValue?: string;
  targetValue?: string;
  redacted?: string;
}

interface DefaultSettingsDiffSC {
  onlyInSource: SdsEntrySC[];
  onlyInTarget: SdsEntrySC[];
  differs: SdsEntrySC[];
  identical: number;
}

interface BucketCounts {
  onlyInSource: unknown[];
  onlyInTarget: unknown[];
  differs: unknown[];
  identical: number;
}

interface EnvDiffSC {
  domains: {
    documents?: BucketCounts;
    mappings?: BucketCounts;
    defaultSettings?: DefaultSettingsDiffSC;
    webapps?: BucketCounts;
    config?: BucketCounts;
  };
  summary: { driftCount: number; identicalCount: number };
}

/** Full serialized result (structuredContent JSON + all content[].text), the surface AC 27.1.2 says a credential plaintext must never appear in. */
function serializedResult(result: ToolResult): string {
  return (
    JSON.stringify(result.structuredContent) +
    "\n" +
    result.content.map((c) => c.text ?? "").join("\n")
  );
}

describe("iris_env_diff -- Story 27.1 QA additions", () => {
  let sourceHttp: ReturnType<typeof createMockHttp>;
  let targetHttp: ReturnType<typeof createMockHttp>;
  let ctx: ToolContext;

  beforeEach(() => {
    // Distinct default namespaces per mock, mirroring the dev suite's
    // convention (two real profiles with different configured defaults).
    sourceHttp = createMockHttp("HSCUSTOM");
    targetHttp = createMockHttp("SADEMO");
    ctx = createMockCtx(sourceHttp);
    ctx.resolveProfileClient = vi.fn(async (name: string) => {
      if (name === "source") return sourceHttp;
      if (name === "target") return targetHttp;
      throw new ProfileResolutionError(name, ["default", "source", "target"]);
    });
  });

  // ══════════════════════════════════════════════════════════════════
  // Credential redaction (AC 27.1.2) -- gaps beyond the dev suite
  // ══════════════════════════════════════════════════════════════════

  describe("defaultSettings credential redaction -- gaps beyond the dev suite", () => {
    it("redacts a credential-ish setting present on ONLY THE TARGET side as [REDACTED] -- the bucket the dev suite's onlyInSource-only test does not cover", async () => {
      sourceHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) return envelope({ settings: [], count: 0 });
        return envelope([]);
      });
      targetHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [sdsRow({ setting: "SecretToken", value: "only-target-plaintext-42" })],
            count: 1,
          });
        }
        return envelope([]);
      });

      const result = await envDiffTool.handler(
        { source: "source", target: "target", domains: ["defaultSettings"], namespace: "HSCUSTOM" },
        ctx,
      );
      expect(result.isError).toBeUndefined();
      const sc = result.structuredContent as unknown as EnvDiffSC;
      const d = sc.domains.defaultSettings as DefaultSettingsDiffSC;
      expect(d.onlyInTarget).toEqual([
        { production: "MyProd", item: "MyItem", hostClass: "MyHost", setting: "SecretToken", value: "[REDACTED]" },
      ]);
      expect(serializedResult(result)).not.toContain("only-target-plaintext-42");
    });

    it("kitchen sink: FOUR differently-shaped credential settings (mixed-case password/secret/key/underscore names) across onlyInSource/onlyInTarget/differs/identical never leak their plaintext anywhere in the serialized result, while a plain non-credential setting mixed into the same call stays visible", async () => {
      const onlySrcSecret = "ONLYSRC-PLAINTEXT-9f3a1";
      const onlyTgtSecret = "ONLYTGT-PLAINTEXT-7b2c2";
      const differsSrcSecret = "DIFFERS-SRC-PLAINTEXT-11aa";
      const differsTgtSecret = "DIFFERS-TGT-PLAINTEXT-22bb";
      const sharedSecret = "SHARED-IDENTICAL-PLAINTEXT-33cc";
      const visibleValue = "42-VISIBLE-NONCREDENTIAL-VALUE";

      sourceHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [
              sdsRow({ setting: "DbPassword", value: onlySrcSecret }), // onlyInSource, "password" substring
              sdsRow({ setting: "encryptionKEY", value: differsSrcSecret }), // differs, "key" substring
              sdsRow({ setting: "Client_Secret", value: sharedSecret }), // identical, "secret" + underscore
              sdsRow({ setting: "RetryCount", value: visibleValue }), // onlyInSource, non-credential
            ],
            count: 4,
          });
        }
        return envelope([]);
      });
      targetHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [
              sdsRow({ setting: "MySecretThing", value: onlyTgtSecret }), // onlyInTarget, "Secret" mixed case
              sdsRow({ setting: "encryptionKEY", value: differsTgtSecret }),
              sdsRow({ setting: "Client_Secret", value: sharedSecret }),
            ],
            count: 3,
          });
        }
        return envelope([]);
      });

      const result = await envDiffTool.handler(
        { source: "source", target: "target", domains: ["defaultSettings"], namespace: "HSCUSTOM" },
        ctx,
      );
      expect(result.isError).toBeUndefined();

      const serialized = serializedResult(result);
      for (const secret of [onlySrcSecret, onlyTgtSecret, differsSrcSecret, differsTgtSecret, sharedSecret]) {
        expect(serialized).not.toContain(secret);
      }
      expect(serialized).toContain(visibleValue);

      const sc = result.structuredContent as unknown as EnvDiffSC;
      const d = sc.domains.defaultSettings as DefaultSettingsDiffSC;

      expect(d.onlyInSource).toEqual([
        { production: "MyProd", item: "MyItem", hostClass: "MyHost", setting: "DbPassword", value: "[REDACTED]" },
        { production: "MyProd", item: "MyItem", hostClass: "MyHost", setting: "RetryCount", value: visibleValue },
      ]);
      expect(d.onlyInTarget).toEqual([
        { production: "MyProd", item: "MyItem", hostClass: "MyHost", setting: "MySecretThing", value: "[REDACTED]" },
      ]);
      expect(d.differs).toEqual([
        {
          production: "MyProd",
          item: "MyItem",
          hostClass: "MyHost",
          setting: "encryptionKEY",
          redacted: "[REDACTED:differs]",
        },
      ]);
      expect(d.differs[0]).not.toHaveProperty("sourceValue");
      expect(d.differs[0]).not.toHaveProperty("targetValue");
      expect(d.identical).toBe(1); // Client_Secret -- same value both sides.
    });

    it("matches on the setting NAME only, never the value -- a credential-LOOKING value under a non-matching name is shown unredacted", async () => {
      sourceHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [sdsRow({ setting: "ProxyURL", value: "http://user:hunter2@proxy.local" })],
            count: 1,
          });
        }
        return envelope([]);
      });
      targetHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/interop/defaultsettings")) return envelope({ settings: [], count: 0 });
        return envelope([]);
      });

      const result = await envDiffTool.handler(
        { source: "source", target: "target", domains: ["defaultSettings"], namespace: "HSCUSTOM" },
        ctx,
      );
      const sc = result.structuredContent as unknown as EnvDiffSC;
      const d = sc.domains.defaultSettings as DefaultSettingsDiffSC;
      expect(d.onlyInSource).toEqual([
        {
          production: "MyProd",
          item: "MyItem",
          hostClass: "MyHost",
          setting: "ProxyURL",
          value: "http://user:hunter2@proxy.local",
        },
      ]);
    });
  });

  // ══════════════════════════════════════════════════════════════════
  // Per-profile namespace routing on the wire (mappings, defaultSettings)
  // ══════════════════════════════════════════════════════════════════

  describe("per-profile namespace routing on the wire", () => {
    it("mappings: each side's 3 GET calls (global/routine/package) carry ITS OWN resolved namespace when 'namespace' is omitted", async () => {
      sourceHttp.get.mockResolvedValue(envelope([]));
      targetHttp.get.mockResolvedValue(envelope([]));
      await envDiffTool.handler({ source: "source", target: "target", domains: ["mappings"] }, ctx);

      const sourcePaths = sourceHttp.get.mock.calls.map((c) => c[0] as string);
      const targetPaths = targetHttp.get.mock.calls.map((c) => c[0] as string);
      expect(sourcePaths).toHaveLength(3);
      expect(targetPaths).toHaveLength(3);
      expect(sourcePaths.every((p) => p.includes("namespace=HSCUSTOM"))).toBe(true);
      expect(targetPaths.every((p) => p.includes("namespace=SADEMO"))).toBe(true);
      // The two sides must genuinely differ -- not both silently defaulting
      // to the same (e.g. always-source) namespace.
      expect(sourcePaths.some((p) => p.includes("namespace=SADEMO"))).toBe(false);
      expect(targetPaths.some((p) => p.includes("namespace=HSCUSTOM"))).toBe(false);
    });

    it("defaultSettings: each side's GET call carries ITS OWN resolved namespace when 'namespace' is omitted", async () => {
      sourceHttp.get.mockResolvedValue(envelope({ settings: [], count: 0 }));
      targetHttp.get.mockResolvedValue(envelope({ settings: [], count: 0 }));
      await envDiffTool.handler({ source: "source", target: "target", domains: ["defaultSettings"] }, ctx);

      expect(sourceHttp.get.mock.calls[0]?.[0]).toContain("namespace=HSCUSTOM");
      expect(targetHttp.get.mock.calls[0]?.[0]).toContain("namespace=SADEMO");
    });
  });

  // ══════════════════════════════════════════════════════════════════
  // Full 5-domain roll-up (AC 27.1.3)
  // ══════════════════════════════════════════════════════════════════

  describe("roll-up across all five domains at once", () => {
    it("sums driftCount/identicalCount correctly across documents+mappings+defaultSettings+webapps+config, each with distinct, deliberately varied bucket counts", async () => {
      sourceHttp.post.mockImplementation(async (path: string) => {
        if (path.includes("/dev/doc/hashes")) {
          return envelope({
            documents: [
              { name: "OnlySrcDoc.cls", hash: "H1", timestamp: "2026-01-01 00:00:00.000" },
              { name: "DiffDoc.cls", hash: "HS", timestamp: "2026-01-01 00:00:00.000" },
              { name: "SameDoc1.cls", hash: "HX", timestamp: "2026-01-01 00:00:00.000" },
              { name: "SameDoc2.cls", hash: "HY", timestamp: "2026-01-01 00:00:00.000" },
            ],
            count: 4,
          });
        }
        if (path.includes("/system/config")) {
          return envelope({ section: "config", properties: configProps({ Maxprocesses: 100 }) });
        }
        throw new Error(`unexpected source POST ${path}`);
      });
      targetHttp.post.mockImplementation(async (path: string) => {
        if (path.includes("/dev/doc/hashes")) {
          return envelope({
            documents: [
              { name: "OnlyTgtDoc.cls", hash: "H2", timestamp: "2026-01-01 00:00:00.000" },
              { name: "DiffDoc.cls", hash: "HT", timestamp: "2026-01-01 00:00:00.000" },
              { name: "SameDoc1.cls", hash: "HX", timestamp: "2026-01-01 00:00:00.000" },
              { name: "SameDoc2.cls", hash: "HY", timestamp: "2026-01-01 00:00:00.000" },
            ],
            count: 4,
          });
        }
        if (path.includes("/system/config")) {
          return envelope({ section: "config", properties: configProps({ Maxprocesses: 200 }) });
        }
        throw new Error(`unexpected target POST ${path}`);
      });

      sourceHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/config/mapping/global")) {
          return envelope([
            mappingRow({ name: "OnlySrcMap" }),
            mappingRow({ name: "DiffMap", database: "DBA" }),
            mappingRow({ name: "SameMap", database: "DBX" }),
          ]);
        }
        if (path.includes("/config/mapping/")) return envelope([]); // routine, package
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [
              sdsRow({ setting: "S1", value: "v1" }),
              sdsRow({ setting: "S2", value: "v2" }),
              sdsRow({ setting: "S3", value: "v3" }),
            ],
            count: 3,
          });
        }
        if (path.includes("/security/webapp")) {
          return envelope([webappRow({ name: "/api/onlysrc" }), webappRow({ name: "/api/same" })]);
        }
        throw new Error(`unexpected source GET ${path}`);
      });
      targetHttp.get.mockImplementation(async (path: string) => {
        if (path.includes("/config/mapping/global")) {
          return envelope([
            mappingRow({ name: "DiffMap", database: "DBZ" }),
            mappingRow({ name: "SameMap", database: "DBX" }),
          ]);
        }
        if (path.includes("/config/mapping/")) return envelope([]);
        if (path.includes("/interop/defaultsettings")) {
          return envelope({
            settings: [
              sdsRow({ setting: "S1", value: "v1" }),
              sdsRow({ setting: "S2", value: "v2" }),
              sdsRow({ setting: "S3", value: "v3" }),
              sdsRow({ setting: "OnlyTgtSetting", value: "v4" }),
            ],
            count: 4,
          });
        }
        if (path.includes("/security/webapp")) {
          return envelope([webappRow({ name: "/api/onlytgt" }), webappRow({ name: "/api/same" })]);
        }
        throw new Error(`unexpected target GET ${path}`);
      });

      const result = await envDiffTool.handler(
        {
          source: "source",
          target: "target",
          domains: ["documents", "mappings", "defaultSettings", "webapps", "config"],
          spec: "A.cls",
        },
        ctx,
      );
      expect(result.isError).toBeUndefined();
      const sc = result.structuredContent as unknown as EnvDiffSC;

      // Sanity-check each domain's own bucket counts first -- the ground
      // truth the roll-up below must sum.
      expect(sc.domains.documents!.onlyInSource).toHaveLength(1);
      expect(sc.domains.documents!.onlyInTarget).toHaveLength(1);
      expect(sc.domains.documents!.differs).toHaveLength(1);
      expect(sc.domains.documents!.identical).toBe(2);

      expect(sc.domains.mappings!.onlyInSource).toHaveLength(1);
      expect(sc.domains.mappings!.onlyInTarget).toHaveLength(0);
      expect(sc.domains.mappings!.differs).toHaveLength(1);
      expect(sc.domains.mappings!.identical).toBe(1);

      expect(sc.domains.defaultSettings!.onlyInSource).toHaveLength(0);
      expect(sc.domains.defaultSettings!.onlyInTarget).toHaveLength(1);
      expect(sc.domains.defaultSettings!.differs).toHaveLength(0);
      expect(sc.domains.defaultSettings!.identical).toBe(3);

      expect(sc.domains.webapps!.onlyInSource).toHaveLength(1);
      expect(sc.domains.webapps!.onlyInTarget).toHaveLength(1);
      expect(sc.domains.webapps!.differs).toHaveLength(0);
      expect(sc.domains.webapps!.identical).toBe(1);

      expect(sc.domains.config!.onlyInSource).toHaveLength(0);
      expect(sc.domains.config!.onlyInTarget).toHaveLength(0);
      expect(sc.domains.config!.differs).toHaveLength(1);
      expect(sc.domains.config!.identical).toBe(10);

      // documents: 1+1+1=3 drift, 2 identical
      // mappings: 1+0+1=2 drift, 1 identical
      // defaultSettings: 0+1+0=1 drift, 3 identical
      // webapps: 1+1+0=2 drift, 1 identical
      // config: 0+0+1=1 drift, 10 identical
      // total drift = 3+2+1+2+1 = 9; total identical = 2+1+3+1+10 = 17
      expect(sc.summary.driftCount).toBe(9);
      expect(sc.summary.identicalCount).toBe(17);
    });
  });
});
